server:
  port: 8888
spring:  profiles:    active:    - native
  cloud:    config:      server:        native:          search-locations:          - file:///D:/Develop/repositoriosGit/gitKraken/spmia-configuration-server/src/main/resources/config/spmia-licensing-service
          - file:///D:/Develop/repositoriosGit/gitKraken/spmia-configuration-server/src/main/resources/config/spmia-organization-service
          - file:///D:/Develop/repositoriosGit/gitKraken/spmia-configuration-server/src/main/resources/config/spmia-zuul-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/carnellj/config-repo/
#          search-paths:#          - licensingservice
#          - organizationservice
#          username: native-cloud-apps
#          password: 0ffended